### ISSUE TITLE
how to sovle the problem '/usr/local/lib/python2.7/dist-packages/pyksc/dist.so: undefined symbol: cblas_dnrm2'

### ISSUE THREAD

**Issue by icahan** [flaviovdf/pyksc#3]
we use the code in ubuntu and when we import the pyksc,how to sovle the problem '/usr/local/lib/python2.7/dist-packages/pyksc/dist.so: undefined symbol: cblas_dnrm2'

**Comment by flaviovdf** [comment]
Install these packages with apt-get:

libblas-dev: Basic Linear Algebra Subroutines 3, static library
libblas3: Basic Linear Algebra Reference implementations, shared library
libblas3gf: Transitional package for libblas

Let me know if it helps

**Comment by icahan** [comment]
Thank you for your reply!
we try this method, but it didn't work and still have the same problem.
Shoud we reinstall pyksc after install these three packages?

**Comment by flaviovdf** [comment]
Please try it. Let me know if it works.

--
Flavio

**Comment by icahan** [comment]
Hi, flaviovdf
Thank you for your help! It works! We reinstalled pyksc by the following steps:

first, we install the three packages you mentioned;

second,we install BLAS and CBLAS as we find them in the code 
we compile blas:
gfortran -c  -O3 *.f  
ar rv libblas.a *.o  
su cp libblas.a /usr/local/lib

we compile cblas:
cp ../BLAS/libblas.a  testing  
make 
sudo cp lib/cblas_LINUX.a /usr/local/lib/libcblas.a 

last, we install pyksc
and thank you very much!

**Comment by flaviovdf** [comment]
Glad it worked.
