### ISSUE TITLE
Example File

### ISSUE THREAD

**Issue by hardikmeisheri** [flaviovdf/pyksc#4]
Hey can you share example run of your implementation?

**Comment by ArunkumarUNCC** [comment]
Hi,

I'm trying to install the pyksc package. I'm getting the following error(s):

running install
running build
running build_py
running build_ext
cythoning pyksc\dhwt.pyx to pyksc\dhwt.c

Error compiling Cython file:
------------------------------------------------------------
...
#-*- coding: utf8
^
------------------------------------------------------------

pyksc\dhwt.pyx:1:0: 'pyksc\dhwt' is not a valid module name
building 'pyksc\dhwt' extension

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\abagavat\AppData\Local\Continuum\Anaconda3\envs\ResearchEnv\lib\site-packages\numpy\core\include -IC:\Users\abagavat\AppData\Local\Continuum\Anaconda3\
envs\ResearchEnv\include -IC:\Users\abagavat\AppData\Local\Continuum\Anaconda3\envs\ResearchEnv\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files
 (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Window
s Kits\8.1\include\\winrt" "-IC:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin\" /Tcpyksc\dhwt.c /Fobuild\temp.win-amd64-3.5\Release\pyksc\dhwt.obj -fopenmp -msse -msse2 -mfpmath=sse

cl : Command line error D8003 : missing source filename

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\cl.exe' failed with exit status 2

Some help would be really appreciated!

**Comment by flaviovdf** [comment]
I don't code on a windows machine, so I'm not sure how to go about your
problem. It seems to be related to visual studio. Could you try to build
the program using bash for windows or cygwin?

--
Flavio

**Comment by ArunkumarUNCC** [comment]
Hi Flaviovdf,

Thanks for the reply. I tried to build the program using Bash for Windows and it worked after installing some packages as you mentioned in the other thread. Now I have to look into how to use the pyksc package in my Windows machine. Thanks again.

**Comment by diegopso** [comment]
+1 looking for a sample to use the lib

**Comment by allesklarbeidir** [comment]
Actually, what you do is simple:

1. You run the setup script and compile the cython library.
2. Then you can import the builded pyksc folder from `./src/build/<some build name, for me (lib.macosx-10.12-x86_64-3.6)>/pyksc` or just the ksc.py file from it using `from pyksc import ksc`, where pyksc is the folder mentioned before
3. now just use the function ksc.ksc(...)
4. the data has to be in the format of an array where each row is a timeseries (list of numeric values) and all timeseries have to have the same length.

Hope that helps

**Comment by flaviovdf** [comment]
Closing this issue based on @allesklarbeidir response. Please also look at the examples in the scripts folder.
