### ISSUE TITLE
Algorithm Input format

### ISSUE THREAD

**Issue by ArunkumarUNCC** [flaviovdf/pyksc#5]
Hi,

I'm little bit confused with what format of inputs should I give to the algorithm ksc. In the test code, input was given as:

X = np.array([[1.0,1,1],
                      [1.1,1,1],
                      [1.2,1,1],
                      [1.3,1,1],
                      [1.3,1,1],
                      ................
                      ................
                      [90,2002,90],
                      [90,2003,90]])

Does this mean the input array represent the format of 
[(item1,time,frequency) ,
 (item1,time,frequency) ,
 ......................
 (item2,time,frequency) ,
 ....]
????????

Waiting for the reply!

**Comment by flaviovdf** [comment]
You don't need to represent time. The code assumes equally spaced measurements.
