### ISSUE TITLE
How to visualize the output?

### ISSUE THREAD

**Issue by fronchetti** [flaviovdf/pyksc#8]
Hello developers,

I would like to know how do you use matplotlib (or another visualization module) to plot the output of the pyksc script. I executed the ksc() method using my time series array, and I got the centroids, assign, best_shift, etc. But I don't know properly how to visualize them. Could you please help me?

Thanks in advance

**Comment by flaviovdf** [comment]
In the scripts folder there are some plotting examples. Please have a look
at them. The algorithm returns a matrix of centroids, so plotting each line
should help you visualize the clusters. You can also plot some examples
based on assign.

This library was created for research purposes. Please look at the examples.

--
Flavio

On Wed, Jul 25, 2018 at 7:22 PM, Felipe Fronchetti <notifications@github.com
